### ISSUE TITLE
Cannot Access Methods of $this-object

### ISSUE THREAD

**Issue by DevilsJin** [yiisoft/yii2-smarty#10]
I set up Yii2 with [smarty extension](https://github.com/yiisoft/yii2-smarty). 

Now I am trying to simply convert the `layouts/main.php` file to a smarty template. For that I need access to the current `yii\web\View` object which is given from the extension as [`$this`-smarty-variable](https://github.com/yiisoft/yii2-smarty/blob/master/docs/guide/template-syntax.md#additional-variables).

I've validated that the smarty `$this` variable was the same as the view-object through `var_dump()`-ing and comparing both.

### Problem
According to the smarty3 docs I should be able to call a method on the `$this`-object from smarty templates like this: `{var_dump($this->head())}`.

Applying the above script in a template just always returns `NULL` which let me guess that no method call had happen.

### Question
How can I call a method from an object which is given to smarty from PHP ?

1. Define variable for use in smarty: `$template->assign('app', \Yii::$app);`
2. Call method on variable in smarty template: `{$app->getSession();}`

What am I doing wrong ?
(my current smarty layout: [pastebin](http://pastebin.com/PWBTmFnZ))

#### If this is no issue to Yii2-Smarty
I'm sorry if this doesn't affect Yii2-Smarty at all but I cant figure out what/why it is not working since this code should work according to Yii2-Smarty and Smarty itself.

I've also asked this question on [stackoverflow](http://stackoverflow.com/questions/31304708/yii2-smarty-cannot-access-methods-of-this-object) though nobody has yet answered.

**Comment by cebe** [comment]
> Applying the above script in a template just always returns NULL which let me guess that no method call had happen.

the `head()` method does not return anything so if you see null that is correct: http://www.yiiframework.com/doc-2.0/yii-web-view.html#head%28%29-detail

You can call the method like this:

```php
{$this->head()}
```

**Comment by DevilsJin** [comment]
Okey, but then how do I include the assets from my project in the `layout/main.tpl` ?
Thought it were done through the `yii\web\View::head()` method but now I can't find it.

**Comment by cebe** [comment]
the head method does that, but it does not return them, it sets a marker that is later replaced.
