### ISSUE TITLE
Smarty Yii2 Syantax Problem

### ISSUE THREAD

**Issue by MustafaVartech** [yiisoft/yii2-smarty#13]
I want this code on smarty;

<?php
echo GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        'id',
        [
            'label' => 'Galeri Adı',
            'value' => function ($data) {  return $data->title; },
        ],
        [
            'label' => 'Galeri Tipi',
            'value' => function ($data) use ($types) {  return $types[$data->type_id]; },
        ],
        [
            'label'=>'Status',
            'value'=>function ($data) {
                return $data->status==1?'Aktif':'Pasif';
            },
        ],
        [
            'class'    => 'yii\grid\ActionColumn',
            'header'   => 'Kontrol',
            'template' => '{view} {update} {delete}',
        ],
    ],
]);
?>

But i don't use. Because this is a syantax problem 'function ($data) { .. }'

I tried everything but I could not find the solution. Help please.

My English is bad. Sorry.

**Comment by samdark** [comment]
Well, obviously smarty doesn't accept PHP. Use Smarty syntax.

**Comment by freezy-sk** [comment]
@MustafaVartech You can solve this by creating some helper class with static functions and use it like this:
```smarty
{use class='yii\grid\GridView' type='function'}
{GridView columns=[
            [
                'value' => ['app\helpers\GridHelper', 'yourGridColumnTitleValue']
            ]
]}
```

```php
class GridHelper
{
    public static function yourGridColumnTitleValue($data)
    {
        return $types[$data->type_id];
    }
}
```

**Comment by MustafaVartech** [comment]
I'm already using such;

{GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        'id',
        [
            'label' => 'Galeri Adı',
            'value' => function ($data) {  return $data->title; },
        ],
        [
            'label' => 'Galeri Tipi',
            'value' => function ($data) use ($types) {  return $types[$data->type_id]; },
        ],
        [
            'label'=>'Status',
            'value'=>function ($data) {
                return $data->status==1?'Aktif':'Pasif';
            },
        ],
        [
            'class'    => 'yii\grid\ActionColumn',
            'header'   => 'Kontrol',
            'template' => '{view} {update} {delete}',
        ],
    ],
])}


But it doesn't work

**Comment by freezy-sk** [comment]
@MustafaVartech it does not work because Smarty does not support closures. That's why you have to move it to static class like I showed you

**Comment by MustafaVartech** [comment]
@freezy-sk Thanks but, i don't understand how use it. its function 'yourGridColumnTitleValue' how use on my example.

**Comment by freezy-sk** [comment]
@MustafaVartech
this is just example and you have to adjust it to fit your application
- 1. create `GridHelper.php` in `app/helpers/` with this content
```php
<?php
namespace app\helpers;

class GridHelper
{
    public static function galeriTitleValue($data)
    {
        return $data->title;
    }

    public static function galeriStatusValue($data)
    {
        return $data->status==1?'Aktif':'Pasif';
    }
}
```

- 2. format your smarty template like this
```smarty
{use class='yii\grid\GridView'}
{GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        'id',
        [
            'label' => 'Galeri Adı',
            'value' => ['app\helpers\GridHelper', 'galeriTitleValue']
        ],
        [
            'label'=>'Status',
            'value' => ['app\helpers\GridHelper', 'galeriStatusValue']
        ],
        [
            'class' => 'yii\grid\ActionColumn',
            'header' => 'Kontrol'
        ]
    ]
])}
```

**Comment by MustafaVartech** [comment]
@freezy-sk very thanks. you're good human.

**Comment by freezy-sk** [comment]
@MustafaVartech you are welcome :)
I forget to tell you that if you want return only attribute of model without modifications, there is no need to define it as custom value.

Instead of this
```smarty
[
    'label' => 'Galeri Adı',
    'value' => ['app\helpers\GridHelper', 'galeriTitleValue']
],
```
you can define it like this
```smarty
[
    'label' => 'Galeri Adı',
    'attribute' => 'title'
],
```

**Comment by MustafaVartech** [comment]
Ok man. very thanks :)

**Comment by MustafaVartech** [comment]
Hi man, again me :)

i try for action column, but i don't

```
[
                    'class'         => 'yii\grid\ActionColumn',
                    'header'        => 'Kontrol',
                    'template'      => '{update} {delete}',
                    'urlCreator'    => ["common\my\grid\helper\Assistant", "PermissionActionUrlCreator"]
 ],
```

```
class Assistant 
{
    public static function PermissionActionUrlCreator($action, $model, $key, $index)
    {
        if ($action === 'update') {
            return Url::to(['assistant/permission/updatea', 'name' => $key]);
        }
        if ($action === 'delete') {
            return Url::to(['assistant/permission/deletea', 'name' => $key]);
        }
    }
```

**Comment by freezy-sk** [comment]
@MustafaVartech where is the problem? it's throwing some error on you?

**Comment by MustafaVartech** [comment]
@freezy-sk no error. but it doesn't work.

**Comment by freezy-sk** [comment]
@MustafaVartech if you want some help, you must provide more informations. from "it doesn't work" I can't know where is your problem.

**Comment by MustafaVartech** [comment]
@freezy-sk i'm sorry. My English is bad. İ try tell. Your method succeed for 'value' veriable. But i want use for 'urlCreator' veriable. But your method doesn't work for 'urlCreator'. it's not throwing error on page. Just doesn't succeed/work. I hope, i can tell.

**Comment by freezy-sk** [comment]
@MustafaVartech this should work for `urlCreator` because there is different check than in `value`.
```
{use class='common\my\grid\helper\Assistant'}
[
                    'class'         => 'yii\grid\ActionColumn',
                    'header'        => 'Kontrol',
                    'template'      => '{update} {delete}',
                    'urlCreator'    => Assistant::PermissionActionUrlCreator()
 ],
```

```
public static function PermissionActionUrlCreator()
    {
        return function($action, $model, $key, $index) {
            if ($action === 'update') {
                return Url::to(['assistant/permission/updatea', 'name' => $key]);
            }
            if ($action === 'delete') {
                return Url::to(['assistant/permission/deletea', 'name' => $key]);
            }
        };
    }
```

**Comment by MustafaVartech** [comment]
@freezy-sk you're good. very very thanks.

**Comment by samdark** [comment]
@freezy-sk do you have time to improve docs of the extension?

**Comment by freezy-sk** [comment]
@samdark sure :) I was thinking about it today

**Comment by samdark** [comment]
Awesome.

**Comment by freezy-sk** [comment]
@samdark here is PR related to that small issue when urlCreator must be hacked like I shown today to Mustafa. https://github.com/yiisoft/yii2/pull/10056

**Comment by MustafaVartech** [comment]
it's good :)
