### ISSUE TITLE
Not compatible with Smarty 2

### ISSUE THREAD

**Issue by antonmarin** [yiisoft/yii2-smarty#17]
### Additional info

No setCompileDir method
| Q                | A
| ---------------- | ---
| Yii vesion       |
| PHP version      |
| Operating system |

**Comment by samdark** [comment]
It is. Should work with either 2.6 or 3. If you have a specific problem, please elaborate it.

**Comment by antonmarin** [comment]
ViewRenderer calls setCompileDir(), which doesn't exist in Smarty

**Comment by samdark** [comment]
Yes. It seems to be added in 3.1. Before it was `$smarty->compile_dir = "foo";`.

**Comment by samdark** [comment]
Fixed.

**Comment by antonmarin** [comment]
Don't think that is is enough. For example: version 2.6.24. Class Smarty doesn't have method setCacheDir(). What about adapter for v2?

**Comment by cebe** [comment]
@samdark just tried to fix support for v2 but it seems nearly every function of the ViewRenderer and Extension class depend on something that only works in smarty 3. Not sure there is any sense in supporting 2.x I have committed my changes to https://github.com/yiisoft/yii2-smarty/pull/20 if someone wants to give it a try.

**Comment by samdark** [comment]
Actually that's a very good question. @antonmarin why do you need v2 supported? Seems v3 is stable and requirements aren't higher than Yii ones...

**Comment by antonmarin** [comment]
Legacy support ((

**Comment by samdark** [comment]
So you do support it already somehow? Probably you can share some code?

**Comment by antonmarin** [comment]
I'm going to create adapter for 2nd version this weekend. Our current solution is ugly

**Comment by samdark** [comment]
Please pick up travis changes @cebe proposed so test run against both versions.

**Comment by antonmarin** [comment]
Yep, thanks

**Comment by antonmarin** [comment]
Well. I need some help )) Any ideas about ->registerClass method?

**Comment by samdark** [comment]
Looks like there's no way to implement it.
