### ISSUE TITLE
A lean fork

### ISSUE THREAD

**Issue by U-D13** [yiisoft/yii2-smarty#18]
I have [forked] this repo for research purposes and cleaned up the history quite a bit. All committer and tag information has been preserved.

At the time of writing this repo has 4606 commits (9.61 MiB), my fork — 76 (54.60 KiB). I would recommend doing a `master` and tags reset here.

[forked]: //github.com/U-D13/yii2-smarty

**Comment by samdark** [comment]
I see no sense in dong that.
