### ISSUE TITLE
Issue with block not callable or registered

### ISSUE THREAD

**Issue by eymerich** [yiisoft/yii2-smarty#23]
### What steps will reproduce the problem?
We have a template with several widgets and PJAX inside some of them where it's defined inside templates.
When we land on home as guest, then proceede to login and go back to the user area (the one with these widgets) here we have and exception raised.

### What's expected?
Templates shown as expected, without an exception raised.

### What do you get instead?
Exception about a block not being registered or callable.

### Additional info
We have found this to be a suitable fix:
https://github.com/yiisoft/yii2-smarty/compare/master...sercanto:master

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.12
| PHP version      | 7.0.12
| Operating system | Ubuntu 16.10

**Comment by samdark** [comment]
Would you please create a pull request?
