### ISSUE TITLE
视图层太不友好了

### ISSUE THREAD

**Issue by forwardliwu** [yiisoft/yii2-smarty#34]
### Additional info

| Q                  | A
| ------------------ | ---
| Yii version        |
| Yii Smarty version |
| Smarty version     |
| PHP version        |
| Operating system   |

为什么没有像TP5那样的视图层   你这个视图层还有PHP标签 
应该没有这些标签阿  希望视图层改成TP5那样的
前后端工程师如何配合,难度也太大了,设计这个框架的工程师估计没有考虑到这一块吧
希望改进,否则从YII转TP和Laravel的很多人

**Comment by machour** [comment]
Hi

I'm afraid Google translate isn't performing really well. From my understanding you're wondering why Yii didn't support the ThinkPHP5 template engine?

**Comment by samdark** [comment]
That's out of scope of what we're supporting. The View component could be extended to support it but we're not going to maintain implementation for it. Feel free to check extensions and if there's nothing yet, implement one.
